
import { GoogleGenAI } from "@google/genai";
import { ProcessingOptions, RenderStyle } from "../types";

export const processSketchUpImage = async (
  base64Image: string,
  options: ProcessingOptions
): Promise<string> => {
  const modelName = (options.imageSize === '2K' || options.imageSize === '4K') 
    ? 'gemini-3-pro-image-preview' 
    : 'gemini-2.5-flash-image';

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const imageData = base64Image.split(',')[1];

  const envPrompts = {
    downtown: "The building is located in a high-end downtown area. Windows MUST reflect skyscrapers and urban city lights. Ground should be realistic dark asphalt or polished granite. Background features a blurred metropolitan skyline.",
    forest: "The building is nestled in a lush green forest. Windows MUST show sharp reflections of trees and foliage. Lighting is filtered through leaves, creating soft organic shadows. Background features dense woodland and soft natural mist.",
    interior: "INTERIOR RENDERING MODE. No external HDRI reflections. Lighting is generated by indoor sources: artificial LED lights, spotlights, and warm ambient glow. Focus on soft Global Illumination (GI) and light bouncing off walls. Textures must include fabric, wood, and smooth plaster with high-quality Ambient Occlusion shadows."
  };

  const stylePrompts: Record<RenderStyle, string> = {
    [RenderStyle.PHOTOREALISTIC]: `ULTRA-PHOTOREALISTIC V-RAY RENDER. Use advanced Ray-Tracing. Fresnel reflections on all surfaces. PBR Materials.`,
    [RenderStyle.REALISTIC]: `Professional Enscape/Lumion style render. High-fidelity architectural visualization.`,
    [RenderStyle.NIGHT_VIEW]: `V-Ray Night Render. Warm 2700K lighting setup. Moody atmosphere.`,
    [RenderStyle.WATERCOLOR]: `Professional architectural watercolor, fine arts style.`,
    [RenderStyle.SKETCH]: `Architectural hand-drawn line-work with graphite shading.`,
    [RenderStyle.CYBERPUNK]: `Futuristic architectural lighting with high neon saturation.`,
    [RenderStyle.CLAY_MODEL]: `Matte white architectural plaster model, studio soft-box lighting.`
  };

  const userInstructionPrompt = options.customInstruction 
    ? `\nSPECIAL USER PRE-RENDER INSTRUCTIONS: ${options.customInstruction}\n`
    : "";

  const prompt = `
    ACT AS A SENIOR ARCHITECTURAL VISUALIZATION ARTIST.
    OBJECTIVE: Transform this SketchUp screenshot into a professional-grade render.
    
    ${userInstructionPrompt}

    CORE CONSTRAINTS: 
    - Maintain ${options.preserveDetails}% architectural accuracy.
    - Preserving the exact structural geometry is mandatory.
    - MODE: ${envPrompts[options.environment]}.
    - LIGHTING: ${options.lighting} setup.
    - RENDERING STYLE: ${stylePrompts[options.style]}.
    
    FINAL QUALITY: Cinematic, sharp focus, professional materials. NO "PAINTING" FILTERS unless watercolor/sketch is selected.
  `;

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [
          { inlineData: { data: imageData, mimeType: 'image/png' } },
          { text: prompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: options.aspectRatio,
          imageSize: options.imageSize === '1K' ? "1K" : options.imageSize
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("فشلت عملية الرندر في استرجاع الصورة.");
  } catch (error: any) {
    console.error("Gemini Error:", error);
    throw new Error(error.message || "حدث خطأ غير متوقع أثناء الرندر.");
  }
};

export const editRenderedImage = async (
  base64Image: string,
  editPrompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const imageData = base64Image.split(',')[1];

  const fullPrompt = `
    TASK: EDIT ARCHITECTURAL RENDER.
    USER REQUEST: ${editPrompt}.
    INSTRUCTIONS: Keep architecture 100% consistent with the provided image. Only apply requested modifications. Adjust lighting/shadows for new objects. Return ONLY the image data.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { data: imageData, mimeType: 'image/png' } },
          { text: fullPrompt }
        ]
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("لم يتم إرجاع صورة معدلة.");
  } catch (error: any) {
    throw new Error(error.message || "حدث خطأ أثناء تعديل الصورة.");
  }
};
